### ISSUE TITLE
404: Page not found

### ISSUE THREAD

**Issue by je-santos** [huiselilun/Palabos-UserGuide#1]
Howdy,

I get a page not found error when trying to access:

https://github.com/huiselilun/Palabos-UserGuide/blob/master/Input-Output.md/#InputOutput

Thanks a lot!

Best,
javier

**Comment by huiselilun** [comment]
Hello javier,

Thanks for your issue. I have fixed it. Please check the below one:

https://github.com/huiselilun/Palabos-UserGuide/blob/master/InputOutput.md/#InputOutput

Best,
JeffHugh
